name: IFC tech
title: IFC tech site

description: Interchange model for construction related industries
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: ""
    values:
      fullversion: "IFC2.3.1.0"
      version: "IFC2.3.1.0"
      githubbranch: "master"
      docsbranch: "master"
      versions:
        - fullversion: "IFC4.1.0.3"
          version: "IFC4.1.0.3"
          githubbranch: "IFC4.1.0.3"
          docsbranch: "release-4.1.0.3"
          url: https://ifc-tech.org/docs/home/
        - fullversion: "IFC4.0.2.0"
          version: "IFC4.0.2.0"
          githubbranch: "IFC4.0.2.0"
          docsbranch: "release-4.0.2.0"
          url: https://ifc4-0-2-0.docs.kubernetes.io/docs/home/
        - fullversion: "IFC2.3.1.0"
          version: "IFC2.3.1.0"
          githubbranch: "IFC2.3.1.0"
          docsbranch: "release-2.3.1.0"
          url: https://ifc2-3-1-0.docs.kubernetes.io/docs/
      deprecated: true
      currentUrl: https://ifc-tech.org/docs/home/
  -
    scope:
      path: "docs"
    values:
      layout: docwithnav
      showedit: true

permalink: pretty

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# SEO
logo: /images/rose.png
twitter:
  username: buildingSMART

# Tables of contents, stored in the _data folder, that control the sidebar nav
tocs:
  - docs-home
  - guides
  - tutorials
  - concepts
  - reference
  - tools
  - samples
  - support

url: http://localhost:4000
