name: IFC tech
title: IFC tech site

description: Interchange model for construction related industries
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: ""
    values:
      ## version: "v1.5.1"
      githubbranch: "master"
      docsbranch: "master"
  -
    scope:
      path: "docs"
    values:
      layout: docwithnav
      showedit: true

permalink: pretty

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# SEO
logo: /images/rose.png
twitter:
  username: buildingSMART

# Tables of contents, stored in the _data folder, that control the sidebar nav
tocs:
  - docs-home
  - guides
  - tutorials
  - concepts
  - reference
  - tools
  - samples
  - support

url: http://localhost:4000
